{% set version = '1.4.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rgbif
  version: {{ version|replace("-", "_") }}

source:

  git_url: https://github.com/ropensci/rgbif
  git_tag: v1.4.0

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, knitr, sp, rgeos, png, raster, protolite (>= 2.0), sf, vcr
requirements:
  build:
    - {{posix}}filesystem        # [win]
    - {{posix}}git
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-crul >=0.7.4
    - r-data.table
    - r-geoaxe
    - r-ggplot2
    - r-jsonlite >=1.6
    - r-lazyeval
    - r-magrittr
    - r-oai >=0.2.2
    - r-tibble
    - r-whisker
    - r-wicket >=0.4.0
    - r-xml2

  run:
    - r-base
    - r-crul >=0.7.4
    - r-data.table
    - r-geoaxe
    - r-ggplot2
    - r-jsonlite >=1.6
    - r-lazyeval
    - r-magrittr
    - r-oai >=0.2.2
    - r-tibble
    - r-whisker
    - r-wicket >=0.4.0
    - r-xml2

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rgbif')"           # [not win]
    - "\"%R%\" -e \"library('rgbif')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/ropensci/rgbif (devel), https://docs.ropensci.org/rgbif (documentation),
    https://ropenscilabs.github.io/occurrence-manual/ (user manual)

  license: MIT
  summary: A programmatic interface to the Web Service methods provided by the Global Biodiversity
    Information Facility ('GBIF'; <https://www.gbif.org/developer/summary>). 'GBIF'
    is a database of species occurrence records from sources all over the globe. 'rgbif'
    includes functions for searching for taxonomic names, retrieving information on
    data providers, getting species occurrence records, getting counts of occurrence
    records, and using the 'GBIF' tile map service to make 'rasters' summarizing huge
    amounts of data.

  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

# The original CRAN metadata for this package was:

# Package: rgbif
# Title: Interface to the Global 'Biodiversity' Information Facility API
# Description: A programmatic interface to the Web Service methods provided by the Global Biodiversity Information Facility ('GBIF'; <https://www.gbif.org/developer/summary>). 'GBIF' is a database of species occurrence records from sources all over the globe. 'rgbif' includes functions for searching for taxonomic names, retrieving information on data providers, getting species occurrence records, getting counts of occurrence records, and using the 'GBIF' tile map service to make 'rasters' summarizing huge amounts of data.
# Version: 1.4.0
# License: MIT + file LICENSE
# Authors@R: c( person("Scott", "Chamberlain", role = c("aut", "cre"), email = "myrmecocystus@gmail.com", comment = c(ORCID="0000-0003-1444-9135")), person("Damiano", "Oldoni", role = "aut", comment = c(ORCID = "0000-0003-3445-7562")), person("Vijay", "Barve", role = "ctb", comment = c(ORCID = "0000-0002-4852-2567")), person("Peter", "Desmet", role = "ctb", comment = c(ORCID = "0000-0002-8442-8025")), person("Laurens", "Geffert", role = "ctb"), person("Dan", "Mcglinn", role = "ctb", comment = c(ORCID = "0000-0003-2359-3526")), person("Karthik", "Ram", role = "ctb", comment = c(ORCID = "0000-0002-0233-1757")) )
# URL: https://github.com/ropensci/rgbif (devel), https://docs.ropensci.org/rgbif (documentation), https://ropenscilabs.github.io/occurrence-manual/ (user manual)
# BugReports: https://github.com/ropensci/rgbif/issues
# LazyData: true
# LazyLoad: true
# VignetteBuilder: knitr
# Roxygen: list(markdown = TRUE)
# Encoding: UTF-8
# Language: en-US
# Imports: xml2, ggplot2, crul (>= 0.7.4), data.table, whisker, magrittr, jsonlite (>= 1.6), oai (>= 0.2.2), geoaxe, tibble, wicket (>= 0.4.0), lazyeval
# Suggests: testthat, knitr, sp, rgeos, png, raster, protolite (>= 2.0), sf, vcr
# RoxygenNote: 6.1.1
# X-schema.org-applicationCategory: Biodiversity
# X-schema.org-keywords: GBIF, specimens, API, web-services, occurrences, species, taxonomy
# X-schema.org-isPartOf: https://ropensci.org

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
